# Site settings
title: SPL Content
baseurl: "/spl-content"
collections:
    pages:
        output: true
prose:
    rooturl: "_pages"
    metadata:
        _posts:
            - name: "layout"
              field:
                element: "hidden"
            - name: "title"
              field:
                element: "hidden"
# Build settings
markdown: kramdown
