# Site settings
title: Skokie Public Library
baseurl: "/spl-content"
collections:
    content:
        output: true
prose:
    rooturl: "_content"
    metadata:
        _posts:
            - name: "layout"
              field:
                element: "hidden"
            - name: "title"
              field:
                element: "hidden"
# Build settings
markdown: kramdown
